
  const data = [
    {
        id: 1,
        title: '01 Sura Al Fatiha',
        audio: require('@/assets/audio/1/audio.mp3'),
        duration: 37669,
        artwork: require('@/assets/thumbnails/1.png'),
      },
     {
        id: 2,
        title: '02 Sura Baqara',
        audio: require('@/assets/audio/2/audio.mp3'),
        duration: 7183647,
        artwork: require('@/assets/thumbnails/2.png'),
      },
     {
        id: 3,
        title: '03 Sura Al Imran',
        audio: require('@/assets/audio/3/audio.mp3'),
        duration: 4223896,
        artwork: require('@/assets/thumbnails/3.png'),
      },
     {
        id: 4,
        title: '04 Sura An Nisa',
        audio: require('@/assets/audio/4/audio.mp3'),
        duration: 4075180,
        artwork: require('@/assets/thumbnails/4.png'),
      },
     {
        id: 5,
        title: '05 Sura Al Maeda',
        audio: require('@/assets/audio/5/audio.mp3'),
        duration: 2970070,
        artwork: require('@/assets/thumbnails/5.png'),
      },
     {
        id: 6,
        title: '06 Sura Al Anaam',
        audio: require('@/assets/audio/6/audio.mp3'),
        duration: 3354540,
        artwork: require('@/assets/thumbnails/6.png'),
      },
     {
        id: 7,
        title: '07 Sura Al Araf',
        audio: require('@/assets/audio/7/audio.mp3'),
        duration: 3726132,
        artwork: require('@/assets/thumbnails/7.png'),
      },
     {
        id: 8,
        title: '08 Sura Anfal',
        audio: require('@/assets/audio/8/audio.mp3'),
        duration: 1420016,
        artwork: require('@/assets/thumbnails/8.png'),
      },
     {
        id: 9,
        title: '09 Sura At Taubah',
        audio: require('@/assets/audio/9/audio.mp3'),
        duration: 2823393,
        artwork: require('@/assets/thumbnails/9.png'),
      },
     {
        id: 10,
        title: '10 Sura Yunus',
        audio: require('@/assets/audio/10/audio.mp3'),
        duration: 2003226,
        artwork: require('@/assets/thumbnails/0.png'),
      },
     {
        id: 11,
        title: '11 Sura Hud',
        audio: require('@/assets/audio/11/audio.mp3'),
        duration: 2185352,
        artwork: require('@/assets/thumbnails/1.png'),
      },
     {
        id: 12,
        title: '12 Sura Yusuf',
        audio: require('@/assets/audio/12/audio.mp3'),
        duration: 2021486,
        artwork: require('@/assets/thumbnails/2.png'),
      },
     {
        id: 13,
        title: '13 Sura Ar Rad',
        audio: require('@/assets/audio/13/audio.mp3'),
        duration: 930560,
        artwork: require('@/assets/thumbnails/3.png'),
      },
     {
        id: 14,
        title: '14 Sura Ibrahim',
        audio: require('@/assets/audio/14/audio.mp3'),
        duration: 912013,
        artwork: require('@/assets/thumbnails/4.png'),
      },
     {
        id: 15,
        title: '15 Sura Al Hijr',
        audio: require('@/assets/audio/15/audio.mp3'),
        duration: 743288,
        artwork: require('@/assets/thumbnails/5.png'),
      },
     {
        id: 16,
        title: '16 Sura An Nahl',
        audio: require('@/assets/audio/16/audio.mp3'),
        duration: 1964878,
        artwork: require('@/assets/thumbnails/6.png'),
      },
     {
        id: 17,
        title: '17 Sura Bani Israil',
        audio: require('@/assets/audio/17/audio.mp3'),
        duration: 1718335,
        artwork: require('@/assets/thumbnails/7.png'),
      },
     {
        id: 18,
        title: '18 Sura Al Kahf',
        audio: require('@/assets/audio/18/audio.mp3'),
        duration: 1798060,
        artwork: require('@/assets/thumbnails/8.png'),
      },
     {
        id: 19,
        title: '19 Sura Maryam',
        audio: require('@/assets/audio/19/audio.mp3'),
        duration: 1104744,
        artwork: require('@/assets/thumbnails/9.png'),
      },
     {
        id: 20,
        title: '20 Sura Taha',
        audio: require('@/assets/audio/20/audio.mp3'),
        duration: 1516826,
        artwork: require('@/assets/thumbnails/0.png'),
      },
     {
        id: 21,
        title: '21 Sura Al Anbia',
        audio: require('@/assets/audio/21/audio.mp3'),
        duration: 1320150,
        artwork: require('@/assets/thumbnails/1.png'),
      },
     {
        id: 22,
        title: '22 Sura Al Hajj',
        audio: require('@/assets/audio/22/audio.mp3'),
        duration: 1424300,
        artwork: require('@/assets/thumbnails/2.png'),
      },
     {
        id: 23,
        title: '23 Sura Al Mumenoon',
        audio: require('@/assets/audio/23/audio.mp3'),
        duration: 1214302,
        artwork: require('@/assets/thumbnails/3.png'),
      },
     {
        id: 24,
        title: '24 Sura An Noor',
        audio: require('@/assets/audio/24/audio.mp3'),
        duration: 1395513,
        artwork: require('@/assets/thumbnails/4.png'),
      },
     {
        id: 25,
        title: '25 Sura Al Furqan',
        audio: require('@/assets/audio/25/audio.mp3'),
        duration: 1005349,
        artwork: require('@/assets/thumbnails/5.png'),
      },
     {
        id: 26,
        title: '26 Sura Ash Shuara',
        audio: require('@/assets/audio/26/audio.mp3'),
        duration: 1535399,
        artwork: require('@/assets/thumbnails/6.png'),
      },
     {
        id: 27,
        title: '27 Sura An Naml',
        audio: require('@/assets/audio/27/audio.mp3'),
        duration: 1362965,
        artwork: require('@/assets/thumbnails/7.png'),
      },
     {
        id: 28,
        title: '28 Sura Al Qasas',
        audio: require('@/assets/audio/28/audio.mp3'),
        duration: 1536026,
        artwork: require('@/assets/thumbnails/8.png'),
      },
     {
        id: 29,
        title: '29 Sura Al Ankaboot',
        audio: require('@/assets/audio/29/audio.mp3'),
        duration: 1077499,
        artwork: require('@/assets/thumbnails/9.png'),
      },
     {
        id: 30,
        title: '30 Sura Ar Room',
        audio: require('@/assets/audio/30/audio.mp3'),
        duration: 905953,
        artwork: require('@/assets/thumbnails/0.png'),
      },
     {
        id: 31,
        title: '31 Sura Lukman',
        audio: require('@/assets/audio/31/audio.mp3'),
        duration: 547579,
        artwork: require('@/assets/thumbnails/1.png'),
      },
     {
        id: 32,
        title: '32 Sura As Sajda',
        audio: require('@/assets/audio/32/audio.mp3'),
        duration: 394632,
        artwork: require('@/assets/thumbnails/2.png'),
      },
     {
        id: 33,
        title: '33 Sura Al Ahzab',
        audio: require('@/assets/audio/33/audio.mp3'),
        duration: 1315840,
        artwork: require('@/assets/thumbnails/3.png'),
      },
     {
        id: 34,
        title: '34 Sura Saba',
        audio: require('@/assets/audio/34/audio.mp3'),
        duration: 903079,
        artwork: require('@/assets/thumbnails/4.png'),
      },
     {
        id: 35,
        title: '35 Sura Fatir',
        audio: require('@/assets/audio/35/audio.mp3'),
        duration: 807079,
        artwork: require('@/assets/thumbnails/5.png'),
      },
     {
        id: 36,
        title: '36 Sura YaSeen',
        audio: require('@/assets/audio/36/audio.mp3'),
        duration: 884506,
        artwork: require('@/assets/thumbnails/6.png'),
      },
     {
        id: 37,
        title: '37 Sura As Saaffat',
        audio: require('@/assets/audio/37/audio.mp3'),
        duration: 1120836,
        artwork: require('@/assets/thumbnails/7.png'),
      },
     {
        id: 38,
        title: '38 Sura Sad',
        audio: require('@/assets/audio/38/audio.mp3'),
        duration: 831399,
        artwork: require('@/assets/thumbnails/8.png'),
      },
     {
        id: 39,
        title: '39 Sura Az Zumar',
        audio: require('@/assets/audio/39/audio.mp3'),
        duration: 1224777,
        artwork: require('@/assets/thumbnails/9.png'),
      },
     {
        id: 40,
        title: '40 Sura Mumin',
        audio: require('@/assets/audio/40/audio.mp3'),
        duration: 1235618,
        artwork: require('@/assets/thumbnails/0.png'),
      },
     {
        id: 41,
        title: '41 Sura Ha Mim As Sajdah',
        audio: require('@/assets/audio/41/audio.mp3'),
        duration: 893753,
        artwork: require('@/assets/thumbnails/1.png'),
      },
     {
        id: 42,
        title: '42 Sura Ash Shura',
        audio: require('@/assets/audio/42/audio.mp3'),
        duration: 877401,
        artwork: require('@/assets/thumbnails/2.png'),
      },
     {
        id: 43,
        title: '43 Sura Az Zukhruf',
        audio: require('@/assets/audio/43/audio.mp3'),
        duration: 919798,
        artwork: require('@/assets/thumbnails/3.png'),
      },
     {
        id: 44,
        title: '44 Sura Ad Dukhan',
        audio: require('@/assets/audio/44/audio.mp3'),
        duration: 387396,
        artwork: require('@/assets/thumbnails/4.png'),
      },
     {
        id: 45,
        title: '45 Sura Al Jathiya',
        audio: require('@/assets/audio/45/audio.mp3'),
        duration: 517251,
        artwork: require('@/assets/thumbnails/5.png'),
      },
     {
        id: 46,
        title: '46 Sura Al Ahkaf',
        audio: require('@/assets/audio/46/audio.mp3'),
        duration: 695745,
        artwork: require('@/assets/thumbnails/6.png'),
      },
     {
        id: 47,
        title: '47 Sura Muhammad',
        audio: require('@/assets/audio/47/audio.mp3'),
        duration: 634018,
        artwork: require('@/assets/thumbnails/7.png'),
      },
     {
        id: 48,
        title: '48 Sura Al Fatah',
        audio: require('@/assets/audio/48/audio.mp3'),
        duration: 619886,
        artwork: require('@/assets/thumbnails/8.png'),
      },
     {
        id: 49,
        title: '49 Sura Al Hujraat',
        audio: require('@/assets/audio/49/audio.mp3'),
        duration: 372715,
        artwork: require('@/assets/thumbnails/9.png'),
      },
     {
        id: 50,
        title: '50 Sura Kahf',
        audio: require('@/assets/audio/50/audio.mp3'),
        duration: 448522,
        artwork: require('@/assets/thumbnails/0.png'),
      },
     {
        id: 51,
        title: '51 Sura Az Zariyat',
        audio: require('@/assets/audio/51/audio.mp3'),
        duration: 430054,
        artwork: require('@/assets/thumbnails/1.png'),
      },
     {
        id: 52,
        title: '52 Sura At Tur',
        audio: require('@/assets/audio/52/audio.mp3'),
        duration: 363468,
        artwork: require('@/assets/thumbnails/2.png'),
      },
     {
        id: 53,
        title: '53 Sura An Najm',
        audio: require('@/assets/audio/53/audio.mp3'),
        duration: 406335,
        artwork: require('@/assets/thumbnails/3.png'),
      },
     {
        id: 54,
        title: '54 Sura Kamar',
        audio: require('@/assets/audio/54/audio.mp3'),
        duration: 469525,
        artwork: require('@/assets/thumbnails/4.png'),
      },
     {
        id: 55,
        title: '55 Sura Ar Rahman',
        audio: require('@/assets/audio/55/audio.mp3'),
        duration: 498965,
        artwork: require('@/assets/thumbnails/5.png'),
      },
     {
        id: 56,
        title: '56 Sura Al Waqia',
        audio: require('@/assets/audio/56/audio.mp3'),
        duration: 483422,
        artwork: require('@/assets/thumbnails/6.png'),
      },
     {
        id: 57,
        title: '57 Sura Al Hadid',
        audio: require('@/assets/audio/57/audio.mp3'),
        duration: 667638,
        artwork: require('@/assets/thumbnails/7.png'),
      },
     {
        id: 58,
        title: '58 Sura Al Mujadila',
        audio: require('@/assets/audio/58/audio.mp3'),
        duration: 515422,
        artwork: require('@/assets/thumbnails/8.png'),
      },
     {
        id: 59,
        title: '59 Sura Al Hashr',
        audio: require('@/assets/audio/59/audio.mp3'),
        duration: 491233,
        artwork: require('@/assets/thumbnails/9.png'),
      },
     {
        id: 60,
        title: '60 Sura Al Momtahina',
        audio: require('@/assets/audio/60/audio.mp3'),
        duration: 369084,
        artwork: require('@/assets/thumbnails/0.png'),
      },
     {
        id: 61,
        title: '61 Sura As Saff',
        audio: require('@/assets/audio/61/audio.mp3'),
        duration: 228545,
        artwork: require('@/assets/thumbnails/1.png'),
      },
     {
        id: 62,
        title: '62 Sura Al Zumua',
        audio: require('@/assets/audio/62/audio.mp3'),
        duration: 191530,
        artwork: require('@/assets/thumbnails/2.png'),
      },
     {
        id: 63,
        title: '63 Sura Al Munafiqun',
        audio: require('@/assets/audio/63/audio.mp3'),
        duration: 198452,
        artwork: require('@/assets/thumbnails/3.png'),
      },
     {
        id: 64,
        title: '64 Sura At Taghabun',
        audio: require('@/assets/audio/64/audio.mp3'),
        duration: 299154,
        artwork: require('@/assets/thumbnails/4.png'),
      },
     {
        id: 65,
        title: '65 Sura At Talaq',
        audio: require('@/assets/audio/65/audio.mp3'),
        duration: 330162,
        artwork: require('@/assets/thumbnails/5.png'),
      },
     {
        id: 66,
        title: '66 Sura At Tahrim',
        audio: require('@/assets/audio/66/audio.mp3'),
        duration: 298344,
        artwork: require('@/assets/thumbnails/6.png'),
      },
     {
        id: 67,
        title: '67 Sura Al Mulk',
        audio: require('@/assets/audio/67/audio.mp3'),
        duration: 419135,
        artwork: require('@/assets/thumbnails/7.png'),
      },
     {
        id: 68,
        title: '68 Sura Al Qalam',
        audio: require('@/assets/audio/68/audio.mp3'),
        duration: 400144,
        artwork: require('@/assets/thumbnails/8.png'),
      },
     {
        id: 69,
        title: '69 Sura Al Haaqqa',
        audio: require('@/assets/audio/69/audio.mp3'),
        duration: 327131,
        artwork: require('@/assets/thumbnails/9.png'),
      },
     {
        id: 70,
        title: '70 Sura Al Maarij',
        audio: require('@/assets/audio/70/audio.mp3'),
        duration: 289541,
        artwork: require('@/assets/thumbnails/0.png'),
      },
     {
        id: 71,
        title: '71 Sura Nooh',
        audio: require('@/assets/audio/71/audio.mp3'),
        duration: 284447,
        artwork: require('@/assets/thumbnails/1.png'),
      },
     {
        id: 72,
        title: '72 Sura Al Jinn',
        audio: require('@/assets/audio/72/audio.mp3'),
        duration: 318824,
        artwork: require('@/assets/thumbnails/2.png'),
      },
     {
        id: 73,
        title: '73 Sura Al Muzzammil',
        audio: require('@/assets/audio/73/audio.mp3'),
        duration: 254668,
        artwork: require('@/assets/thumbnails/3.png'),
      },
     {
        id: 74,
        title: '74 Sura Al Muddathir',
        audio: require('@/assets/audio/74/audio.mp3'),
        duration: 338469,
        artwork: require('@/assets/thumbnails/4.png'),
      },
     {
        id: 75,
        title: '75 Sura Al Qiyama',
        audio: require('@/assets/audio/75/audio.mp3'),
        duration: 216555,
        artwork: require('@/assets/thumbnails/5.png'),
      },
     {
        id: 76,
        title: '76 Sura Ad Dahr',
        audio: require('@/assets/audio/76/audio.mp3'),
        duration: 304248,
        artwork: require('@/assets/thumbnails/6.png'),
      },
     {
        id: 77,
        title: '77 Sura Al Mursalat',
        audio: require('@/assets/audio/77/audio.mp3'),
        duration: 283089,
        artwork: require('@/assets/thumbnails/7.png'),
      },
     {
        id: 78,
        title: '78 Sura An Naba',
        audio: require('@/assets/audio/78/audio.mp3'),
        duration: 230896,
        artwork: require('@/assets/thumbnails/8.png'),
      },
     {
        id: 79,
        title: '79 Sura An Naziat',
        audio: require('@/assets/audio/79/audio.mp3'),
        duration: 240875,
        artwork: require('@/assets/thumbnails/9.png'),
      },
     {
        id: 80,
        title: '80 Sura Abasa',
        audio: require('@/assets/audio/80/audio.mp3'),
        duration: 178233,
        artwork: require('@/assets/thumbnails/0.png'),
      },
     {
        id: 81,
        title: '81 Sura At Takwir',
        audio: require('@/assets/audio/81/audio.mp3'),
        duration: 126511,
        artwork: require('@/assets/thumbnails/1.png'),
      },
     {
        id: 82,
        title: '82 Sura Al Infitar',
        audio: require('@/assets/audio/82/audio.mp3'),
        duration: 87458,
        artwork: require('@/assets/thumbnails/2.png'),
      },
     {
        id: 83,
        title: '83 Sura Al Mutaffifin',
        audio: require('@/assets/audio/83/audio.mp3'),
        duration: 185992,
        artwork: require('@/assets/thumbnails/3.png'),
      },
     {
        id: 84,
        title: '84 Sura Al Inshiqaq',
        audio: require('@/assets/audio/84/audio.mp3'),
        duration: 140878,
        artwork: require('@/assets/thumbnails/4.png'),
      },
     {
        id: 85,
        title: '85 Sura Al Burooj',
        audio: require('@/assets/audio/85/audio.mp3'),
        duration: 139128,
        artwork: require('@/assets/thumbnails/5.png'),
      },
     {
        id: 86,
        title: '86 Sura At Tariq',
        audio: require('@/assets/audio/86/audio.mp3'),
        duration: 80927,
        artwork: require('@/assets/thumbnails/6.png'),
      },
     {
        id: 87,
        title: '87 Sura Al Ala',
        audio: require('@/assets/audio/87/audio.mp3'),
        duration: 103706,
        artwork: require('@/assets/thumbnails/7.png'),
      },
     {
        id: 88,
        title: '88 Sura Al Ghashiya',
        audio: require('@/assets/audio/88/audio.mp3'),
        duration: 114599,
        artwork: require('@/assets/thumbnails/8.png'),
      },
     {
        id: 89,
        title: '89 Sura Al Fajr',
        audio: require('@/assets/audio/89/audio.mp3'),
        duration: 163291,
        artwork: require('@/assets/thumbnails/9.png'),
      },
     {
        id: 90,
        title: '90 Sura Al Balad',
        audio: require('@/assets/audio/90/audio.mp3'),
        duration: 85734,
        artwork: require('@/assets/thumbnails/0.png'),
      },
     {
        id: 91,
        title: '91 Sura Ash Shams',
        audio: require('@/assets/audio/91/audio.mp3'),
        duration: 89522,
        artwork: require('@/assets/thumbnails/1.png'),
      },
     {
        id: 92,
        title: '92 Sura Al Lail',
        audio: require('@/assets/audio/92/audio.mp3'),
        duration: 98873,
        artwork: require('@/assets/thumbnails/2.png'),
      },
     {
        id: 93,
        title: '93 Sura Ad Dhuha',
        audio: require('@/assets/audio/93/audio.mp3'),
        duration: 55484,
        artwork: require('@/assets/thumbnails/3.png'),
      },
     {
        id: 94,
        title: '94 Sura Al Inshirah',
        audio: require('@/assets/audio/94/audio.mp3'),
        duration: 40464,
        artwork: require('@/assets/thumbnails/4.png'),
      },
     {
        id: 95,
        title: '95 Sura At Tin',
        audio: require('@/assets/audio/95/audio.mp3'),
        duration: 41561,
        artwork: require('@/assets/thumbnails/5.png'),
      },
     {
        id: 96,
        title: '96 Sura Al Alaq',
        audio: require('@/assets/audio/96/audio.mp3'),
        duration: 115958,
        artwork: require('@/assets/thumbnails/6.png'),
      },
     {
        id: 97,
        title: '97 Sura Al Qadr',
        audio: require('@/assets/audio/97/audio.mp3'),
        duration: 33280,
        artwork: require('@/assets/thumbnails/7.png'),
      },
     {
        id: 98,
        title: '98 Sura Al Bayyinah',
        audio: require('@/assets/audio/98/audio.mp3'),
        duration: 92447,
        artwork: require('@/assets/thumbnails/8.png'),
      },
     {
        id: 99,
        title: '99 Sura Az Zilzal',
        audio: require('@/assets/audio/99/audio.mp3'),
        duration: 46132,
        artwork: require('@/assets/thumbnails/9.png'),
      },
     {
        id: 100,
        title: '100 Sura Al Adiyat',
        audio: require('@/assets/audio/100/audio.mp3'),
        duration: 56686,
        artwork: require('@/assets/thumbnails/0.png'),
      },
     {
        id: 101,
        title: '101 Sura Al Qaria',
        audio: require('@/assets/audio/101/audio.mp3'),
        duration: 43207,
        artwork: require('@/assets/thumbnails/1.png'),
      },
     {
        id: 102,
        title: '102 Sura At Takasur',
        audio: require('@/assets/audio/102/audio.mp3'),
        duration: 37486,
        artwork: require('@/assets/thumbnails/2.png'),
      },
     {
        id: 103,
        title: '103 Sura Al Asr',
        audio: require('@/assets/audio/103/audio.mp3'),
        duration: 23275,
        artwork: require('@/assets/thumbnails/3.png'),
      },
     {
        id: 104,
        title: '104 Sura Al Humaza',
        audio: require('@/assets/audio/104/audio.mp3'),
        duration: 47073,
        artwork: require('@/assets/thumbnails/4.png'),
      },
     {
        id: 105,
        title: '105 Sura Al Fil',
        audio: require('@/assets/audio/105/audio.mp3'),
        duration: 30354,
        artwork: require('@/assets/thumbnails/5.png'),
      },
     {
        id: 106,
        title: '106 Sura Quraish',
        audio: require('@/assets/audio/106/audio.mp3'),
        duration: 21447,
        artwork: require('@/assets/thumbnails/6.png'),
      },
     {
        id: 107,
        title: '107 Sura Al Maun',
        audio: require('@/assets/audio/107/audio.mp3'),
        duration: 35004,
        artwork: require('@/assets/thumbnails/7.png'),
      },
     {
        id: 108,
        title: '108 Sura Al Kawsar',
        audio: require('@/assets/audio/108/audio.mp3'),
        duration: 21682,
        artwork: require('@/assets/thumbnails/8.png'),
      },
     {
        id: 109,
        title: '109 Sura Al Kafiroon',
        audio: require('@/assets/audio/109/audio.mp3'),
        duration: 35579,
        artwork: require('@/assets/thumbnails/9.png'),
      },
     {
        id: 110,
        title: '110 Sura An Nasr',
        audio: require('@/assets/audio/110/audio.mp3'),
        duration: 24712,
        artwork: require('@/assets/thumbnails/0.png'),
      },
     {
        id: 111,
        title: '111 Sura Al Lahab',
        audio: require('@/assets/audio/111/audio.mp3'),
        duration: 36545,
        artwork: require('@/assets/thumbnails/1.png'),
      },
     {
        id: 112,
        title: '112 Sura Al Ikhlas',
        audio: require('@/assets/audio/112/audio.mp3'),
        duration: 23458,
        artwork: require('@/assets/thumbnails/2.png'),
      },
     {
        id: 113,
        title: '113 Sura Al Falaq',
        audio: require('@/assets/audio/113/audio.mp3'),
        duration: 39367,
        artwork: require('@/assets/thumbnails/3.png'),
      },
     {
        id: 114,
        title: '114 Sura An Nas',
        audio: require('@/assets/audio/114/audio.mp3'),
        duration: 40385,
        artwork: require('@/assets/thumbnails/4.png'),
      }
  ];
  export default data;
